GET http://localhost:3001/recipes

###

GET http://localhost:3001/recipes/65827e64beaa389a4b4eb32b


###

POST http://localhost:3001/recipes/post
Content-Type: application/json

{
    "userid": "87123687137621823",
    "recipename": "Pizza",
    "ingredients": "['ketchi','kek','ajsdnkad']",
    "preparation": "['do this','do that','soak, boil, heat']"
}

###

DELETE http://localhost:3001/recipes/657409d68c37f65c5d50f53a


###

POST  http://localhost:3001/signup
Content-Type: application/json

{
    "name": "Pizza2322",
    "email": "tesasasdssssdastsss@gmail.com",
    "password": "AddRecipe123"
}

###

POST http://localhost:3001/signin
Content-Type: application/json


{
    "email": "badri@badri.com",
    "password": "192427gvBk!("
}

###

PATCH http://localhost:3001/recipes/6582af59c07e70b10afe2991
Content-Type: application/json


{
    "recipename": "kumar",
    "ingredients": "['Bee, Broth, Sugar, Recipes']",
    "preparation": "['Juice, Chocolate, Pizza']"
}

